version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 